global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      #- targets: ['localhost:8081']
      - targets: ['auth-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'business-logic'
    static_configs:
      #- targets: ['localhost:8080']
      - targets: ['business-logic:8080']
    metrics_path: '/actuator/prometheus'
